apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "bold-reports.designer.name" . }}
  namespace: {{ include "bold-reports.namespace" . }}  
  labels: {{- include "common.labels.standard" . | nindent 4 }}
    {{- if .Values.commonLabels }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.commonLabels "context" $ ) | nindent 4 }}
    {{- end }}
  {{- if .Values.commonAnnotations }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }} 
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.designer.replicaCount }}
  {{- end }}
  selector:
    matchLabels: {{- include "bold-reports.designer.matchLabels" . | nindent 6 }}
  template:
    metadata:
      {{- if .Values.podAnnotations }}
      annotations: {{- include "common.tplvalues.render" (dict "value" .Values.podAnnotations "context" $) | nindent 8 }}
      {{- end }}
      labels: {{- include "common.labels.standard" . | nindent 8 }}
        app.kubernetes.io/component: designer
        {{- if .Values.podLabels }}
        {{- include "common.tplvalues.render" (dict "value" .Values.podLabels "context" $) | nindent 8 }}
        {{- end }}
    spec:
      serviceAccountName: {{ include "bold-reports.serviceAccountName" . }}      
      volumes:
        - name: data-volume
          persistentVolumeClaim:
            claimName: {{ include "bold-reports.fileServerName" . }}
            readOnly: false
        - name: log4net-config-volume
          configMap:
            name: {{ include "bold-reports.log4netName" . }}
      containers:
        - name: reports-bold-reports
          image: "{{ .Values.designer.image.registry }}/{{ .Values.designer.image.repository }}:{{ .Values.designer.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.designer.image.pullPolicy }}          
          volumeMounts:
          - mountPath: /application/app_data
            name: data-volume
          - mountPath: /application/reporting/reportservice/logs
            name: log4net-config-volume
          ports:
            - name: http
              containerPort: {{ .Values.designer.container.port }}
              protocol: TCP
          {{- if .Values.designer.readinessProbe -}}        
            {{- include "bold-reports.designer.readinessProbe" . | nindent 10 -}}
          {{- end -}}
          {{- include "bold-reports.designer.env" . | nindent 10 }}
          resources:
            {{- toYaml .Values.designer.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}