apiVersion: v1
kind: Service
metadata:
  name: reports-web-service
  namespace: {{ include "bold-reports.namespace" . }}
  labels: {{- include "common.labels.standard" . | nindent 4 }}
    {{- if .Values.commonLabels }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.commonLabels "context" $ ) | nindent 4 }}
    {{- end }}
spec:
  type: NodePort
  ports:
  - name: reports-web-port
    port: 6550
    targetPort: {{ .Values.reportsWeb.container.port }}
    protocol: TCP
  selector: {{- include "bold-reports.reportsWeb.matchLabels" . | nindent 4 }}    