apiVersion: v1
kind: Service
metadata:
  name: id-api-service
  namespace: {{ include "bold-reports.namespace" . }}
  labels: {{- include "common.labels.standard" . | nindent 4 }}
    {{- if .Values.commonLabels }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.commonLabels "context" $ ) | nindent 4 }}
    {{- end }}
spec:
  type: NodePort
  ports:
  - name: id-api-port
    port: 6001
    targetPort: {{ .Values.idApi.container.port }}
    protocol: TCP
  selector: {{- include "bold-reports.idApi.matchLabels" . | nindent 4 }}    