{{- if .Values.persistence.storageClass.create }}
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: {{ include "bold-reports.persistence.storageClass.name" . }}
provisioner: efs.csi.aws.com
parameters:
  provisioningMode: efs-ap
  fileSystemId: {{ .Values.persistence.storageClass.fileSystemId }}
  directoryPerms: "700"
  gidRangeStart: "1000"
  gidRangeEnd: "2000" 
  basePath: {{ default "/dynamic_provisioning" .Values.persistence.storageClass.basePath }}
{{- end }}
