apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "bold-reports.fullname" . }}
  namespace: {{ include "bold-reports.namespace" . }}
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: {{ .Values.persistence.storageClass.name }}
  resources:
    requests:
      storage: {{ default "4Gi" .Values.persistence.size }}